name: 'Create or Update Discovered APIs'
description: 'Creates or updates the targeted api files'
inputs:
  api-host:
    description: 'Platform API hostname'
    required: true
  api-key:
    description: 'APIC API key'
    required: false
  provider-org:  
    description: 'Name of ID of provider org to us'
    required: true
  api-file:  
    description: 'File name of api to add to apiconnect discovery repo'
    required: true

outputs:
  action-result:
    description: 'Result of operation to add apis to apiconnect discovery repo'  
runs:
  using: 'node16'
  main: 'dist/index.js'
